# Generated by Django 6.0.2 on 2026-02-16 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('LEAVE', 'Leave'), ('HR_REQUEST', 'HR Request'), ('LETTER', 'Letter'), ('ASSET', 'Asset'), ('EXIT', 'Exit'), ('PERFORMANCE', 'Performance'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('doc_type', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('access_scope', models.CharField(default='HR_ONLY', max_length=60)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner_type', 'owner_id'], name='documents_d_owner_t_855562_idx'), models.Index(fields=['doc_type'], name='documents_d_doc_typ_4a1a00_idx')],
            },
        ),
    ]
