# Generated by Django 6.0.2 on 2026-02-16 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('entity_type', models.CharField(db_index=True, max_length=80)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('ip_address', models.CharField(blank=True, max_length=60)),
                ('user_agent', models.TextField(blank=True)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
