# Generated by Django 6.0.2 on 2026-02-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='staff_category',
            field=models.CharField(choices=[('JUNIOR', 'Junior Officer (Regional)'), ('SENIOR', 'Senior Officer'), ('SUPERVISOR', 'Supervisor (RM/Director/Unit Head)')], db_index=True, default='SENIOR', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['staff_category'], name='employees_e_staff_c_67e3b2_idx'),
        ),
    ]
